'use client';
import { useEffect, useMemo, useState } from 'react';
import { Code2, FileText, Download, Play, Save, Trash2, X } from 'lucide-react';
import { createArtifact, deleteArtifact, listArtifacts, updateArtifact, type ArtifactKind, type LooseMouthArtifact } from '@/lib/loosemouth-artifacts';

type Props={accessToken:string;userId:string;conversationId?:string|null;onClose:()=>void};
function appletDoc(content:Record<string,unknown>){
 const files=Array.isArray(content.files)?content.files as Array<{path?:string;content?:string}>:[];
 const get=(p:string)=>files.find(f=>f.path===p)?.content||'';
 const html=get('index.html')||'<main id="app"></main>',css=get('style.css'),js=get('app.js');
 return html.replace(/<\/head>/i,`<style>${css}</style></head>`).replace(/<\/body>/i,`<script>${js.replace(/<\/script/gi,'<\\/script')}<\/script></body>`);
}
export default function LooseMouthWorkbench({accessToken,userId,conversationId,onClose}:Props){
 const [kind,setKind]=useState<ArtifactKind>('report');const [prompt,setPrompt]=useState('');const [items,setItems]=useState<LooseMouthArtifact[]>([]);const [active,setActive]=useState<LooseMouthArtifact|null>(null);const [draft,setDraft]=useState<Record<string,unknown>|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{void listArtifacts(accessToken,userId).then(setItems).catch(e=>setError(e.message));},[accessToken,userId]);
 const preview=useMemo(()=>draft&&kind==='applet'?appletDoc(draft):'',[draft,kind]);
 async function generate(){if(!prompt.trim()||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/intent/artifact',{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({kind,prompt,current:draft})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Generation failed.');setDraft(d.artifact);}catch(e){setError(e instanceof Error?e.message:'Generation failed.');}finally{setBusy(false);}}
 async function save(){if(!draft)return;setBusy(true);try{const title=String(draft.title||active?.title||'Untitled artifact').slice(0,160);let saved;if(active){saved=await updateArtifact(accessToken,userId,active.id,{title,prompt,content:draft,version:active.version+1});}else{saved=await createArtifact(accessToken,userId,{conversation_id:conversationId,kind,title,prompt,content:draft});}setActive(saved);setItems(await listArtifacts(accessToken,userId));}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 function download(){if(!draft)return;if(kind==='report'){const blob=new Blob([String(draft.markdown||'')],{type:'text/markdown'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${String(draft.title||'loosemouth-report').replace(/[^a-z0-9-_]+/gi,'-')}.md`;a.click();URL.revokeObjectURL(a.href);return;}const blob=new Blob([preview],{type:'text/html'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${String(draft.title||'loosemouth-applet').replace(/[^a-z0-9-_]+/gi,'-')}.html`;a.click();URL.revokeObjectURL(a.href);}
 return <section className="fixed inset-0 z-50 bg-slate-950/30 p-0 backdrop-blur-sm lg:p-6">
  <div className="mx-auto grid h-full max-w-[1500px] overflow-hidden bg-white shadow-2xl lg:grid-cols-[250px_1fr] lg:rounded-2xl lg:border lg:border-slate-200">
   <aside className="hidden border-r border-slate-200 bg-slate-50 p-4 lg:block"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-700">LooseMouth Workbench</p><p className="mt-2 text-sm text-slate-600">Saved builds</p><div className="mt-4 space-y-1">{items.map(i=><button key={i.id} onClick={()=>{setActive(i);setKind(i.kind);setDraft(i.content);setPrompt(i.prompt)}} className="w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-white"><span className="block truncate font-medium">{i.title}</span><span className="text-[10px] uppercase text-slate-500">{i.kind} · v{i.version}</span></button>)}</div></aside>
   <div className="flex min-w-0 flex-col"><header className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><p className="text-sm font-semibold">LooseMouth Workbench</p><p className="text-xs text-slate-500">Build, inspect, revise, keep.</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100" aria-label="Close workbench"><X size={18}/></button></header>
   <div className="flex gap-2 border-b border-slate-200 p-3"><button onClick={()=>{setKind('report');setActive(null);setDraft(null)}} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold ${kind==='report'?'bg-slate-950 text-white':'bg-slate-100'}`}><FileText size={15}/>Report</button><button onClick={()=>{setKind('applet');setActive(null);setDraft(null)}} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold ${kind==='applet'?'bg-slate-950 text-white':'bg-slate-100'}`}><Code2 size={15}/>Applet</button></div>
   <div className="grid min-h-0 flex-1 lg:grid-cols-[380px_1fr]"><div className="border-r border-slate-200 p-4"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={kind==='report'?'Describe the report you want…':'Describe the applet you want to build…'} className="h-40 w-full resize-none rounded-xl border border-slate-300 p-3 text-sm outline-none focus:border-blue-500"/><button onClick={generate} disabled={busy||!prompt.trim()} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50"><Play size={15}/>{busy?'Building…':draft?'Revise build':'Build'}</button>{error&&<p className="mt-3 text-xs text-amber-700">{error}</p>}<div className="mt-4 flex gap-2"><button onClick={save} disabled={!draft||busy} className="inline-flex flex-1 items-center justify-center gap-2 rounded-lg border p-2 text-sm"><Save size={14}/>Save</button><button onClick={download} disabled={!draft} className="inline-flex flex-1 items-center justify-center gap-2 rounded-lg border p-2 text-sm"><Download size={14}/>Download</button>{active&&<button onClick={async()=>{await deleteArtifact(accessToken,userId,active.id);setActive(null);setDraft(null);setItems(await listArtifacts(accessToken,userId));}} className="rounded-lg border p-2" aria-label="Delete"><Trash2 size={14}/></button>}</div></div>
   <div className="min-h-0 overflow-auto bg-slate-100 p-4">{!draft?<div className="flex h-full items-center justify-center text-center text-sm text-slate-500">Your {kind} will open here.</div>:kind==='report'?<article className="mx-auto min-h-full max-w-4xl whitespace-pre-wrap rounded-xl bg-white p-6 text-sm leading-7 shadow-sm">{String(draft.markdown||'')}</article>:<iframe title="LooseMouth applet preview" sandbox="allow-scripts" srcDoc={preview} className="h-full min-h-[520px] w-full rounded-xl border border-slate-200 bg-white shadow-sm"/>}</div></div>
   </div>
  </div>
 </section>;
}
