import { NextRequest, NextResponse } from 'next/server';
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from '@/lib/supabase-public';
export const runtime = 'nodejs';
const PRICE_IDS={paid:'price_1UO1qp0ULZCgUuKWA1vgyIOj',enhanced:'price_1UO1qr0ULZCgUuKWTJpXtg6S'} as const;
async function user(req:NextRequest){const a=req.headers.get('authorization');if(!a?.startsWith('Bearer '))return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:a},cache:'no-store'});if(!r.ok)return null;return r.json() as Promise<{id:string,email?:string}>;}
export async function POST(req:NextRequest){const u=await user(req);if(!u)return NextResponse.json({error:'Sign in before upgrading.'},{status:401});const {tier}=await req.json() as {tier?:keyof typeof PRICE_IDS};if(!tier||!PRICE_IDS[tier])return NextResponse.json({error:'Invalid plan.'},{status:400});const key=process.env.STRIPE_SECRET_KEY;if(!key)return NextResponse.json({error:'Billing is not configured.'},{status:503});const origin=req.nextUrl.origin;const form=new URLSearchParams();form.set('mode','subscription');form.set('line_items[0][price]',PRICE_IDS[tier]);form.set('line_items[0][quantity]','1');const secret=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;
let existing:{stripe_customer_id?:string|null;trial_started_at?:string|null;subscription_status?:string|null}|undefined;
if(secret){const ent=new URL('/rest/v1/loosemouth_billing_entitlements',SUPABASE_URL);ent.searchParams.set('select','stripe_customer_id,trial_started_at,subscription_status');ent.searchParams.set('user_id',`eq.${u.id}`);ent.searchParams.set('limit','1');const er=await fetch(ent,{headers:{apikey:secret,Authorization:`Bearer ${secret}`},cache:'no-store'});if(er.ok){const rows=await er.json() as Array<typeof existing>;existing=rows[0];}}
if(existing?.subscription_status&&['active','trialing'].includes(existing.subscription_status))return NextResponse.json({error:'You already have an active subscription. Manage your existing plan instead.'},{status:409});
form.set('client_reference_id',u.id);
if(existing?.stripe_customer_id)form.set('customer',existing.stripe_customer_id);else if(u.email)form.set('customer_email',u.email);
form.set('success_url',`${origin}/intent?billing=success`);form.set('cancel_url',`${origin}/intent?billing=cancelled`);form.set('metadata[user_id]',u.id);form.set('metadata[tier]',tier);if(!existing?.trial_started_at){form.set('subscription_data[trial_period_days]','30');form.set('subscription_data[trial_settings][end_behavior][missing_payment_method]','cancel');}form.set('subscription_data[metadata][user_id]',u.id);form.set('subscription_data[metadata][tier]',tier);const r=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/x-www-form-urlencoded'},body:form});const data=await r.json() as {url?:string;error?:{message?:string}};if(!r.ok||!data.url)return NextResponse.json({error:data.error?.message||'Unable to start checkout.'},{status:502});return NextResponse.json({url:data.url});}