-- Align persisted preferences with the Groq-backed LooseMouth modes and add opt-out usage telemetry.
alter table public.loosemouth_user_preferences
  drop constraint if exists loosemouth_user_preferences_preferred_model_check;

alter table public.loosemouth_user_preferences
  add constraint loosemouth_user_preferences_preferred_model_check
  check (preferred_model = any (array['fast'::text,'medium'::text,'enhanced'::text,'native'::text,'gemma4'::text,'intentR-402'::text]));

alter table public.loosemouth_user_preferences
  add column if not exists data_collection_enabled boolean not null default true;

create table if not exists public.loosemouth_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  session_id uuid,
  mode text not null check (mode in ('fast','medium','enhanced')),
  provider text not null default 'groq',
  provider_model text not null,
  search_enabled boolean not null default false,
  search_depth text check (search_depth is null or search_depth in ('quick','deep')),
  input_chars integer not null check (input_chars >= 0),
  output_chars integer not null check (output_chars >= 0),
  latency_ms integer not null check (latency_ms >= 0),
  created_at timestamptz not null default now()
);

alter table public.loosemouth_usage_events enable row level security;
revoke all on table public.loosemouth_usage_events from anon, authenticated;
revoke all on sequence public.loosemouth_usage_events_id_seq from anon, authenticated;
