-- Mirror of live migration applied through Supabase on 2026-10-07.
create table if not exists public.loosemouth_billing_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  tier text not null default 'free' check (tier in ('free','paid','enhanced')),
  subscription_status text,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  updated_at timestamptz not null default now()
);
alter table public.loosemouth_billing_entitlements enable row level security;
revoke all on public.loosemouth_billing_entitlements from anon, authenticated;
grant select on public.loosemouth_billing_entitlements to authenticated;
drop policy if exists "Users read own billing entitlement" on public.loosemouth_billing_entitlements;
create policy "Users read own billing entitlement" on public.loosemouth_billing_entitlements for select to authenticated using (auth.uid() = user_id);
create index if not exists loosemouth_billing_customer_idx on public.loosemouth_billing_entitlements(stripe_customer_id);
create index if not exists loosemouth_billing_subscription_idx on public.loosemouth_billing_entitlements(stripe_subscription_id);

create table if not exists public.loosemouth_support_contributions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text unique,
  stripe_customer_id text,
  amount_total bigint not null check (amount_total >= 0),
  currency text not null,
  payment_status text not null,
  created_at timestamptz not null default now()
);
alter table public.loosemouth_support_contributions enable row level security;
revoke all on public.loosemouth_support_contributions from anon, authenticated;
grant select on public.loosemouth_support_contributions to authenticated;
drop policy if exists "Users read own support contributions" on public.loosemouth_support_contributions;
create policy "Users read own support contributions" on public.loosemouth_support_contributions for select to authenticated using (auth.uid() = user_id);
