import { Boxes, BrainCircuit, Cpu, FlaskConical, Network, ScanLine, ShieldCheck, Waves } from 'lucide-react';

const programs = [
  { icon: ShieldCheck, title: 'PLM · Private Model Layer', text: 'PLMN, PLMH and PLM Connect form the private-model infrastructure direction: operator-controlled model nodes, hubs, secure connectivity, local memory, signed device identity and auditable inference.' },
  { icon: BrainCircuit, title: 'INTENT · Model Family', text: 'A model-development program spanning compact INTENT models through INTENT-R recurrent language modeling, with Multi-INTENT extending the architecture toward multimodal perception, routing and specialized model cooperation.' },
  { icon: FlaskConical, title: 'Virtual Lab', text: 'A scientific-computing environment designed to connect AI, experiments, sensor acquisition and reproducible evidence. Virtual Lab treats experiments as inspectable systems rather than isolated model demos.' },
  { icon: ScanLine, title: 'Virtual Lab Instruments', text: 'Software-defined instruments and the Instrument Console bring cameras, RF, environmental sensing and future laboratory hardware into synchronized acquisition, measurement, replay and analysis workflows.' },
  { icon: Cpu, title: 'Edge Training AI', text: 'Research into models that can learn, adapt and run closer to the user: browser-native training, WebGPU execution, mobile/edge inference and bounded local retraining instead of requiring every learning loop to live in a remote AI service.' },
  { icon: Waves, title: 'Autonomous Microbiology', text: 'A forward research direction for combining Virtual Lab instruments, machine vision, experiment control and specialized AI into closed-loop microbiology workflows where observations can drive bounded autonomous measurement and experimentation.' },
  { icon: Boxes, title: 'Artifact AI · 3D INTENT', text: 'A spatial and artifact-centered direction for AI that reasons over persistent digital objects, 3D environments and inspectable generated artifacts—not only text conversations. This includes spatial interfaces, 3D representations and executable research artifacts.' },
  { icon: Network, title: 'BitVision', text: 'Tokenizer-free and alternative-representation research exploring bits, visual/bitmap-like representations and specialized scientific variants such as BitVision-MS, with the broader goal of testing representations beyond conventional text token pipelines.' },
];

export default function CompanyVisionSection() {
 return <section id="vision" className="border-b border-slate-200 bg-white py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <div className="max-w-4xl"><p className="text-sm font-semibold text-blue-700">Technical vision</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.03em] text-slate-950 sm:text-5xl">A vertically integrated AI research stack.</h2>
  <p className="mt-6 text-base leading-7 text-slate-600 sm:text-lg">Global Intent Company is being developed around a single thesis: useful AI should be more than a remote model endpoint. Models, private infrastructure, scientific instruments, local learning, multimodal perception and verifiable artifacts can operate as one inspectable system.</p>
  <p className="mt-4 text-sm leading-6 text-slate-500">The programs below include shipped software, active experiments and longer-horizon research directions. They are presented as a roadmap, not as claims that every component is production-complete.</p></div>
  <div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-slate-200 bg-slate-200 md:grid-cols-2">{programs.map(({icon:Icon,title,text})=><article key={title} className="bg-white p-6 sm:p-8"><Icon className="h-5 w-5 text-blue-700"/><h3 className="mt-5 text-lg font-semibold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div>
  <div className="mt-10 rounded-2xl bg-slate-950 p-7 text-white sm:p-9"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-300">How the pieces converge</p><p className="mt-4 max-w-5xl text-lg leading-8 text-slate-200">PLM provides the private execution substrate. INTENT provides model research. Multi-INTENT expands perception across modalities. Virtual Lab and its instruments connect models to measurable scientific environments. Edge training moves adaptation toward devices and browsers. Artifact AI and 3D INTENT make outputs persistent, spatial and inspectable. BitVision tests alternative representations. Autonomous microbiology is a domain where these layers can ultimately converge into bounded, evidence-producing scientific agents.</p></div>
 </div></section>;
}
