import { Cpu, Database, KeyRound, Server } from 'lucide-react';

export default function PLMHSection() {
  const capabilities=[[Server,'Runtime supervision','Host and expose privately operated model runtimes through a consistent service boundary.'],[Database,'Model registry','Represent providers and models through canonical identities and explicit capability discovery.'],[KeyRound,'Authenticated access','Pair devices and authorize model operations rather than treating network reachability as authorization.'],[Cpu,'Provider adapters','Connect local model engines through adapters while keeping the hub protocol stable for clients.']];
  return <section id="plmh" className="border-b border-slate-200 bg-slate-50 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div className="max-w-3xl"><p className="text-sm font-semibold text-blue-700">PLMH · Execution layer</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.03em] text-slate-950 sm:text-4xl">A private hub between model runtimes and applications.</h2><p className="mt-5 text-base leading-7 text-slate-600 sm:text-lg">PLMH is GIC’s hub architecture for operating private models behind a controlled protocol boundary. Its job is to make model discovery, authentication, health, capabilities, and streaming explicit.</p></div>
    <div className="mt-12 grid gap-5 md:grid-cols-2">{capabilities.map(([Icon,title,text]:any)=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><Icon className="h-5 w-5"/></span><div><h3 className="font-semibold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div></div></article>)}</div>
  </div></section>;
}
