import Link from 'next/link';
import { ArrowRight, Beaker, Binary, FlaskConical, Layers3 } from 'lucide-react';

export default function ResearchEngineSection() {
 const areas=[[Binary,'Machine learning','Compact models, training experiments, interpretability, and constrained-compute research.','/research'],[Layers3,'Systems','Runtimes, microkernels, protocols, and inspectable computing architecture.','/systems'],[FlaskConical,'Virtual Lab','Scientific simulation, instrumentation, evidence packaging, and reproducible workflows.','/virtual-lab']];
 return <section id="research-engine" className="border-b border-slate-200 bg-slate-50 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
   <div className="max-w-3xl"><p className="text-sm font-semibold text-blue-700">Research &amp; development</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.03em] text-slate-950 sm:text-4xl">Research is the evidence layer behind the products.</h2><p className="mt-5 text-base leading-7 text-slate-600 sm:text-lg">GIC publishes technical work so architecture claims can be traced back to experiments, source, measured results, and documented limitations.</p></div>
   <div className="mt-12 grid gap-5 md:grid-cols-3">{areas.map(([Icon,title,text,href]:any)=><Link key={title} href={href} className="group rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><Icon className="h-5 w-5 text-blue-700"/><h3 className="mt-8 text-lg font-semibold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-slate-900">Explore <ArrowRight className="h-4 w-4 transition group-hover:translate-x-0.5"/></span></Link>)}</div>
   <div className="mt-8 flex flex-col justify-between gap-5 rounded-2xl bg-slate-950 p-7 text-white sm:flex-row sm:items-center"><div className="flex gap-4"><Beaker className="mt-1 h-5 w-5 shrink-0 text-blue-300"/><div><h3 className="font-semibold">Evidence before claims</h3><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-300">Research pages distinguish measured results, implementation details, design objectives, and open hypotheses rather than presenting them as equivalent evidence.</p></div></div><Link href="/research" className="inline-flex shrink-0 items-center gap-2 text-sm font-semibold">Open research <ArrowRight className="h-4 w-4"/></Link></div>
 </div></section>;
}
